### ISSUE TITLE
No Status tab in Windows version

### ISSUE THREAD

**Issue by Skriptach** [gladiusio/gladius-node-ui#90]
I have updated Gladius Node Manager from 0.6.0 to 0.6.2
And there is no Status tab as described at release notes 
https://medium.com/@gladiusio/development-update-20-7166407e3e68
![image](https://user-images.githubusercontent.com/390735/49144926-41db1e80-f307-11e8-8583-1fd6a5ab4aa6.png)

OS: Windows 7 x64

**Comment by overtfuture** [comment]
This is in the upcoming release, and it is not in the current release 0.6.2. We will be releasing the new UI this week.
